"""
Example: cRPA Downfolding from Mean-Field Solution

CoQuí supports cRPA calculations starting from either:
1. A mean-field object from external DFT results, e.g. Quantum ESPRESSO
2. Electronic structure results generated by CoQuí itself

This example demonstrates how to perform cRPA downfolding using a mean-field solution as input.

The output consists of:
- Vloc: bare local Coulomb tensor
- Wloc_iw: dynamically screened local Coulomb tensor on a Matsubara frequency grid

In addition, all results are written to the checkpoint file under
    scf/iter0/downfolded_model
where scf/iter0 always refers to the initial mean-field solution.

By default, only the local downfolded Coulomb tensors (Vloc, Wloc_iw) are returned and stored.
Non-local (q-dependent) downfolded Coulomb tensors are stored only if q_dependent_output = True in the input parameters.

See also
--------
- cRPA from a MBPT solution: 02_crpa_from_mbpt.py
"""
from mpi4py import MPI
import coqui

qe_dir = coqui.TEST_INPUT_DIR + "qe/svo_kp222_nbnd40/out"
wan_h5 = coqui.TEST_INPUT_DIR + "qe/svo_kp222_nbnd40/mlwf/svo.mlwf.h5"

coqui_mpi = coqui.MpiHandler()
coqui.set_verbosity(coqui_mpi, output_level=1)

# construct MF from a dictionary
mf_params = {
    "prefix": "svo",
    "outdir": qe_dir
}
svo_mf = coqui.make_mf(coqui_mpi, params=mf_params, mf_type="qe")

# construct thc handler and compute the thc integrals during initialization
eri_params = {
    "ecut": svo_mf.ecutwfc()*1.2,
    "thresh": 1e-3,
}
svo_thc = coqui.make_thc_coulomb(mf=svo_mf, params=eri_params)

crpa_params = {
    "screen_type": "crpa", 
    "prefix": "svo",
    "wannier_file": wan_h5, 
    "greens_func_source": "mf", 
    "beta": 200,
    "iaft": {
        "wmax": 2.0, 
        "prec": "medium"
    }
}
Vloc, Wloc_iw = coqui.downfold_coulomb(params=crpa_params, h_int=svo_thc)

