"""
Example: cRPA Downfolding from MBPT Solution

CoQuí supports cRPA calculations starting from either:
1. A mean-field object from external DFT results, e.g. Quantum ESPRESSO
2. Electronic structure results generated by CoQuí itself (MBPT, GW, etc.)

This example demonstrates how to perform cRPA downfolding using a GW solution as input.

The output consists of:
- Vloc: bare local Coulomb tensor
- Wloc_iw: dynamically screened local Coulomb tensor on a Matsubara frequency grid

By CoQuí convention, all results from MBPT solutions are written to the checkpoint file under
    scf/iter{N}/downfolded_model
where N is the iteration number of the MBPT calculation 
(N=0 corresponds to the mean-field solution) 

By default, only the local downfolded Coulomb tensors (Vloc, Wloc_w) are returned and stored.
Non-local (q-dependent) downfolded Coulomb tensors are stored only if q_dependent_output = True in the input parameters.

See also
--------
- cRPA from a mean-field solution: 01_crpa_from_mf.py
"""
from mpi4py import MPI
import coqui

qe_dir = coqui.TEST_INPUT_DIR + "qe/svo_kp222_nbnd40/out"
wan_h5 = coqui.TEST_INPUT_DIR + "qe/svo_kp222_nbnd40/mlwf/svo.mlwf.h5"

coqui_mpi = coqui.MpiHandler()
coqui.set_verbosity(coqui_mpi, output_level=2)

# mean-field
mf_params = {
    "prefix": "svo", 
    "outdir": qe_dir,
    "nbnd": 40
}
svo_mf = coqui.make_mf(coqui_mpi, mf_params, "qe") 

# thc-eri
thc_params = {
    "thresh": 1e-4, 
    "ecut": 60, 
}
svo_thc = coqui.make_thc_coulomb(svo_mf, thc_params)

gw_params = {
    "restart": False,     # read prior GW state if available
    "output":  "svo",     # label/prefix for outputs
    "niter":   1,         # number of Dyson–SCF iterations
    "beta":    300,       # inverse temperature (Ha^{-1})
    "iaft": {
        "wmax": 3.0,
        "prec": "medium"
    }
}
coqui.run_gw(gw_params, h_int=svo_thc)

# no need to specify beta and iaft_prec again; they are read from the checkpoint file
crpa_params = {
    "screen_type": "crpa", 
    "outdir": "./", 
    "prefix": "svo", 
    "wannier_file": wan_h5, 
    "greens_func_source": "scf", 
    "greens_func_iteration": -1, 
    "div_treatment": "gygi_extrplt"
}
Vloc, Wloc_iw = coqui.downfold_coulomb(svo_thc, crpa_params)

